pip install gdown
pip install typing
pip install os
pip install tkinter
pip install PyMuPDF
pip install docx
pip install tqdm
pip install docx2pdf
pip install pylint==3.0.2
pip install mypy==1.7.1
pip install flake8==6.1.0
pip install black==23.11.0
pip install types-tabulate