pip install gdown
pip install typing
pip install os
pip install tk
pip install PyMuPDF
pip install python-docx 
pip install odfpy
pip install tqdm
pip install docx2pdf
pip install pylint==3.0.2
pip install mypy==1.7.1
pip install flake8==6.1.0
pip install black==23.11.0
pip install types-tabulate
pip install tabulate
pip install pandas
pip install openpyxl
pip install slate3k
python CopytoSlate3k.py